[package]
name = "touhoulang_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
touhoulang = { path = "../../TouhouLang" }
serde = { version="1.0", features = ["derive"] }
serde_json = "1.0"
